kinokopedia-server/config/routes.rb
Rails.application.routes.draw do
  resources :mushrooms
end

kinokopedia-server/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

kinokopedia-server/app/models/mushroom.rb
class Mushroom < ApplicationRecord
end

kinokopedia-server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

kinokopedia-server/app/controllers/mushrooms_controller.rb
class MushroomsController < ApplicationController
  before_action :set_mushroom, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  
  # GET /mushrooms
  # GET /mushrooms.json
  def index
    @mushrooms = Mushroom.all
  end

  # GET /mushrooms/1
  # GET /mushrooms/1.json
  def show
  end

  # GET /mushrooms/new
  def new
    @mushroom = Mushroom.new
  end

  # GET /mushrooms/1/edit
  def edit
  end

  # POST /mushrooms
  # POST /mushrooms.json`
  def create
    @mushroom = Mushroom.new(mushroom_params)
    binding.pry
    respond_to do |format|
      if @mushroom.save
        format.html { redirect_to @mushroom, notice: 'Mushroom was successfully created.' }
        format.json { render :show, status: :created, location: @mushroom }
      else
        format.html { render :new }
        format.json { render json: @mushroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mushrooms/1
  # PATCH/PUT /mushrooms/1.json
  def update
    respond_to do |format|
      if @mushroom.update(mushroom_params)
        format.html { redirect_to @mushroom, notice: 'Mushroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @mushroom }
      else
        format.html { render :edit }
        format.json { render json: @mushroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mushrooms/1
  # DELETE /mushrooms/1.json
  def destroy
    @mushroom.destroy
    respond_to do |format|
      format.html { redirect_to mushrooms_url, notice: 'Mushroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mushroom
      @mushroom = Mushroom.find(params[:id])
      
    end

    # Only allow a list of trusted parameters through.
    def mushroom_params
      params.fetch(:mushroom, {}).permit(:latin_name, :common_name, :confused_with, :habitat, :region, :poisonous, :img_url)
    end
end

kinokopedia-server/app/helpers/application_helper.rb
module ApplicationHelper
end

kinokopedia-server/app/helpers/mushrooms_helper.rb
module MushroomsHelper
end

kinokopedia-server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kinokopedia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

kinokopedia-server/app/views/mushrooms/_form.html.erb
<%= form_with(model: mushroom, local: true) do |form| %>
  <% if mushroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mushroom.errors.count, "error") %> prohibited this mushroom from being saved:</h2>

      <ul>
        <% mushroom.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :latin_name %>
    <%= form.text_field :latin_name %>
  </div>

  <div class="field">
    <%= form.label :common_name %>
    <%= form.text_field :common_name %>
  </div>

  <div class="field">
    <%= form.label :confused_with %>
    <%= form.text_field :confused_with %>
  </div>

  <div class="field">
    <%= form.label :habitat %>
    <%= form.text_field :habitat %>
  </div>

  <div class="field">
    <%= form.label :region %>
    <%= form.text_field :region %>
  </div>

  <div class="field">
    <%= form.label :fairy_rings %>
    <%= form.check_box :fairy_rings %>
  </div>

  <div class="field">
    <%= form.label :characteristics %>
    <%= form.text_field :characteristics %>
  </div>

  <div class="field">
    <%= form.label :img_url %>
    <%= form.text_field :img_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

kinokopedia-server/app/views/mushrooms/edit.html.erb
<h1>Editing Mushroom</h1>

<%= render 'form', mushroom: @mushroom %>

<%= link_to 'Show', @mushroom %> |
<%= link_to 'Back', mushrooms_path %>

kinokopedia-server/app/views/mushrooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mushrooms</h1>

<table>
  <thead>
    <tr>
      <th>Latin name</th>
      <th>Common name</th>
      <th>Confused with</th>
      <th>Habitat</th>
      <th>Region</th>
      <th>Fairy rings</th>
      <th>Characteristics</th>
      <th>Img url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mushrooms.each do |mushroom| %>
      <tr>
        <td><%= mushroom.latin_name %></td>
        <td><%= mushroom.common_name %></td>
        <td><%= mushroom.confused_with %></td>
        <td><%= mushroom.habitat %></td>
        <td><%= mushroom.region %></td>
        <td><%= mushroom.poisonous %></td>
        <td><%= mushroom.img_url %></td>
        <td><%= link_to 'Show', mushroom %></td>
        <td><%= link_to 'Edit', edit_mushroom_path(mushroom) %></td>
        <td><%= link_to 'Destroy', mushroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mushroom', new_mushroom_path %>

kinokopedia-server/app/views/mushrooms/new.html.erb
<h1>New Mushroom</h1>

<%= render 'form', mushroom: @mushroom %>

<%= link_to 'Back', mushrooms_path %>

kinokopedia-server/app/views/mushrooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latin name:</strong>
  <%= @mushroom.latin_name %>
</p>

<p>
  <strong>Common name:</strong>
  <%= @mushroom.common_name %>
</p>

<p>
  <strong>Confused with:</strong>
  <%= @mushroom.confused_with %>
</p>

<p>
  <strong>Habitat:</strong>
  <%= @mushroom.habitat %>
</p>

<p>
  <strong>Region:</strong>
  <%= @mushroom.region %>
</p>

<p>
  <strong>Fairy rings:</strong>
  <%= @mushroom.fairy_rings %>
</p>

<p>
  <strong>Characteristics:</strong>
  <%= @mushroom.characteristics %>
</p>

<p>
  <strong>Img url:</strong>
  <%= @mushroom.img_url %>
</p>

<%= link_to 'Edit', edit_mushroom_path(@mushroom) %> |
<%= link_to 'Back', mushrooms_path %>